kind: pipeline
name: schematic
steps:
  - name: garage_test
    image: python:3
    commands:
      - pip install requirements-dev.txt
      - pytest --cov=schematic --cov-fail-under=90
    when:
      event:
        - push
trigger:
  event:
    - push
